import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { setConstantValue } from "typescript";
import Modal from "../components/Modal/Modal";

import activities from "../data/activities.json";

export default function Bored() {
  const [isOpen, setIsOpen] = useState(false);
  const [activityName, setActivityName] = useState("Insert Activity Name Here");
  const [cost, setCost] = useState(0);
  const [stayingIn, setStayingIn] = useState(true);
  const [datesAvailable, setDatesAvailable] = useState("year round");
  const [weekendGetaway, setWeekendGetaway] = useState(true);
  const [neighborhood, setNeighborhood] = useState("any");
  const [isFoodOption, setIsFoodOption] = useState(true);
  const [hasDrinks, sethasDrinks] = useState(true);
  const [haveBeen, setHaveBeen] = useState(false);

  function close() {
    setIsOpen(false);
  }

  function pickActivity() {
    console.log(activities);
    var winner = activities[Math.floor(Math.random() * activities.length)];
    console.log(winner);
    console.log(winner.activity);
    setIsOpen(true);
    setActivityName(winner.activity);
    setCost(winner.cost);
    setStayingIn(winner.stayingIn);
    setDatesAvailable(winner.datesAvailable);
    setWeekendGetaway(winner.weekendGetaway);
    setNeighborhood(winner.neighborhood);
    setIsFoodOption(winner.isFoodOption);
    sethasDrinks(winner.hasDrinks);
    setHaveBeen(winner.haveBeen);
    // what the fuck
    // alert(`Activity: ${winner.activity} Cost: ${winner.cost}`);
  }

  function pickFood() {
    var foodsOnly = activities.filter((obj) => {
      return obj.isFoodOption === true;
    });
    var foodWinner = foodsOnly[Math.floor(Math.random() * foodsOnly.length)];
    alert(foodWinner.activity);
  }

  return (
    <div>
      <Head>
        <title>Activity Picker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {activities.map((activity) => (
        <h1 key={activity.activity}>{activity.activity}</h1>
      ))} */}
      <div
        className="container"
        style={{
          width: "100%",
          height: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <button className="" onClick={pickActivity} style={{ width: "20%" }}>
          Choose an activity
        </button>
        <button style={{ width: "20%", marginTop: "5%" }} onClick={pickFood}>
          Choose some food
        </button>
        <Modal
          isOpen={isOpen}
          close={close}
          activityName={activityName}
          cost={cost}
          stayingIn={stayingIn}
          datesAvailable={datesAvailable}
          weekendGetaway={weekendGetaway}
          neighborhood={neighborhood}
          isFoodOption={isFoodOption}
          hasDrinks={hasDrinks}
          haveBeen={haveBeen}
        />
      </div>
    </div>
  );
}
