import Head from "next/head";
import Link from "next/link";

import colors from "../data/colors.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Colors!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {colors.map((color) => (
        <Link href={`/${color.name}`} key={color.name}>
          <h1>{color.name}</h1>
        </Link>
      ))}
    </div>
  );
}
