import React, { useEffect, useState } from "react";

import Head from "next/head";
import Link from "next/link";
import colors from "../data/colors.json";
import { createClient } from "@sanity/client";

const client = createClient({
  projectId: "zsjkxx81",
  dataset: "production",
  apiVersion: "2023-06-23",
  useCdn: false,
});

// create a groq query to retrieve all colors
const data = await client.fetch(`*[_type == "color"]{name, hexcode}`);
console.log(data);

export default function Home() {
  const [currentData, setCurrentData] = useState([
    "back to the start",
    "another one",
  ]);
  useEffect(() => {
    setCurrentData(data);
  }),
    [data];
  return (
    <div>
      <Head>
        <title>Colors!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {colors.map((color) => (
        <Link href={`/${color.name}`} key={color.name}>
          <h1>{color.name}</h1>
        </Link>
      ))} */}
      {data.map((data: any) => (
        <Link href={`/${data.name}`} key={data.name}>
          <h1>{data.name}</h1>
        </Link>
      ))}
    </div>
  );
}
