import Head from "next/head";
import Link from "next/link";
// import { useRouter } from "next/router";
// import { sanityClient } from "../src/lib/sanity";
// import { groq } from "next-sanity";
import useSWR from "swr";

import colors from "../data/colors.json";

export default function Home() {
  //   const { query } = useRouter();
  //   const { data } = useSWR(groq`*[_type == "color"]`, (query) =>
  //     sanityClient.fetch(query)
  //   ) as {
  //     data: string[];
  //   };
  //   console.log(data);

  return (
    <div>
      <Head>
        <title>Colors!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {colors.map((color) => (
        <Link href={`/${color.name}`} key={color.name}>
          <h1>{color.name}</h1>
        </Link>
      ))}
    </div>
  );
}
